### PR TITLE
Give project a makeover

### PR DESCRIPTION
**Pull request by hannobraun**
Update dependencies, fix warnings, clean some things up.

This PR is a work in progress that currently depends on the master branch of nrf52. I'll update it once nrf52 0.4 has been released on crates.io.

### CODE REVIEW

**Comment by jamesmunns** [comment]
@hannobraun I have published `nrf52` v0.4.0, and invited you as an owner for `nrf52` and `nrf52-hal` on crates.io. Sorry for the delay!

**Review by jamesmunns — APPROVED** [review]
Please update the git dependency, and add yourself as an author. Other than that it LGTM :+1:

**Comment by hannobraun** [comment]
Updates the dependency and added myself as author. Thanks for the review!

**Comment by hannobraun** [comment]
Oh, and don't worry about the delay. Cargo provides enough ways to override dependencies, so I'm not reliant on upstream updates to make progress.

**Pull request merged**
