### PR TITLE
Rename pins to better match documentation

### PR DESCRIPTION
**Pull request by hannobraun**
The product specification refers to single-digit pins as P0.00, P0.01, etc.

### CODE REVIEW

**Review by jamesmunns — APPROVED** [review]
LGTM!

**Comment by hannobraun** [comment]
Thank you!

**Comment by wez** [comment]
Would you mind pushing this to https://github.com/nrf-rs/nrf52 too?

**Comment by hannobraun** [comment]
@wez Will do! Might take me a few days though, quite busy :)

Should we treat https://github.com/nrf-rs/nrf52 as the new upstream now?

**Comment by wez** [comment]
thanks :)
re: new upstream, I think it makes sense to transition soonish otherwise having two possible upstreams will be a net negative.

**Pull request merged**
