### PR TITLE
Re-export some types from top-level module

### PR DESCRIPTION
**Pull request by hannobraun**
~This pull request is based on #4 and #5. I recommend reviewing and merging these pull requests first, before merging this one.~

### CODE REVIEW

**Comment by jamesmunns** [comment]
Hey Hanno,

Still running around the US after RustConf, and taking care of some personal/family stuff. I hope to get caught up by the end of this week.

Feel free to merge anything if it is a blocker for you, but otherwise we can get all of this "upstreamed" later this week.

**Comment by hannobraun** [comment]
Don't worry James, I'm fine over here. Everything's merged in [my fork](https://github.com/braun-robotics/nrf52-hal), so I'm not being blocked by any of these pull requests. Have a great time in the US! I'm looking forward to having you back soon :)

**Comment by hannobraun** [comment]
Rebased, ready for review.

**Review by jamesmunns — APPROVED** [review]
LGTM

**Comment by hannobraun** [comment]
Thank you!

**Pull request merged**
