### PR TITLE
[WIP] Add basic SPIM API

### PR DESCRIPTION
**Pull request by hannobraun**
This pull request is based on #4. I suggest reviewing and merging that separately, then I'll rebase this PR after.

### CODE REVIEW

**Comment by hannobraun** [comment]
I forgot to mention: There's a [usage example](https://github.com/braun-robotics/rust-dwm1001/blob/139f8d54b1a077fee0b66e48af38a589c416feae/examples/dw1000.rs) in the DWM1001 crate.

**Comment by wez** [comment]
This also looks reasonable to me.  Would be nice to have more control over the bus settings :)

**Review by jamesmunns — APPROVED** [review]
LGTM - feel free to rebase after merging #4

**Comment by hannobraun** [comment]
Rebased, merging now.

@wez @jamesmunns Thank you for the review!

**Pull request merged**
